### ISSUE TITLE
Tracing without Performance

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry-go#656]
See https://github.com/getsentry/team-sdks/issues/5
```[tasklist]
### Tasks
- [x] All events are always sent through the /envelope endpoint if performance is enabled. (If possible just always use /envelope) https://github.com/getsentry/sentry-go/pull/631
- [x] Add a mechanism to continue a trace from environment variables.
- [x] All error, transaction and check-in events sent to Sentry always contain a Dynamic Sampling Context (trace) envelope header item.
- [x] All error, transaction and check-in sent to Sentry always contain a trace context.
- [ ] https://github.com/getsentry/sentry-go/pull/862
```
